language: java
sudo: false # faster builds
# first try
before_install:
  - pip install --user codecov

after_success:
  - codecov

os:
  - osx

matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk7
